name: Deploy Node.js App to Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install dependencies and Build
        run: |
          npm ci
          

      - name: Generate deployment package
        run: zip -r deploy.zip . -x "*.git*" "node_modules/*"


      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: 'assignment'
          environment_name: 'Assignment-env'
          version_label: 'deploy-${{ github.sha }}'
          region: 'ap-south-1'
          deployment_package: backend/deploy.zip
          wait_for_deployment: true
          use_existing_version_if_available: true
